#### REDES NEURAIS: DEEP LEARNING COM PYTORCH

In [ ]:
import torch
x = torch.rand(5, 3)
print(x)

In [2]:
lista = [[1,2,3],
         [4,5,6]]
cvt_torch = torch.Tensor(lista)
print(cvt_torch.dtype)
print(cvt_torch)

cvt_torch = torch.FloatTensor(lista)
print(cvt_torch.dtype)
print(cvt_torch)

cvt_torch = torch.DoubleTensor(lista)
print(cvt_torch.dtype)
print(cvt_torch)

cvt_torch = torch.LongTensor(lista)
print(cvt_torch.dtype)
print(cvt_torch)


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
import torch
#Alocando tensor no cuda (mas nao deu certo)
tns = torch.randn(10)
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)

In [4]:
import tensorflow as tf
from tensorflow import keras
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  0


In [5]:
tf.test.is_built_with_cuda()

False